---
title: "Data Documentation"
author: "Michelle Ngo, Chunqi Zhao, Kelly Chang, Eunseo Chung"
date: "2023-12-05"
output: html_document
---

# Data Documentation
The link to the original data source: [Kaggle UberEats Dataset](https://www.kaggle.com/datasets/ahmedshahriarsakib/uber-eats-usa-restaurants-menus/)

## Variables
* id (Restaurant id) - numeric with range 0-363
* position (Restaurant position in UberEats search result) - numeric with range 1-194
* name.y (Restaurant name) - character
* name.x (Menu meal name) - character
* score (Restaurant score) - numeric with range 3.2-5.0
* category (Restaurant category) - character
* avgprice (Average price by restaurant) - numeric with range 0-34
* morethanavg (Price more than $12.60) - numeric with range 0-1
* popular (Position greater than or less than 30) - numeric with range 0-1
* avgscoreinarea (Average score by zip code ) - numeric with range 3.5-5.0
* zip_code (Zip code) - character
* lat (Latitude) - numeric with range 33.2-34.2
* lng (Longitude) - numeric with range -87.1--85.8
* category (Menu category) - character
* name (Menu Name) - character
* description (Menu description) - character
* price (Menu price) - numeric with range 0-130.89

## Basic Summary Statistics
Row: 25000
Column: 15

### NA values 
Description: 7113

Score: 9141

zip_code: 163

avgscoreinarea: 977
