---
title: "Final Project"
author: "Michelle Ngo, Chunqi Zhao, Kelly Chang, Eunseo Chung"
date: "2023-12-01"
output: html_document
---
```{r}
library(readr)
library(tidyverse)
library(ggplot2)
library(maps)
restaurantmenus <- read_delim("Documents/archive/restaurant-menus.csv")
restmen <- restaurantmenus[1:25000, c(1:5)]
write_csv(restmen, file = "Documents/data/restmen.csv")

restaurant <- read_delim("Documents/archive/restaurants.csv")
rest <- restaurant[1:25000, c(1:11)]
write_csv(rest, file = "Documents/data/rest.csv")
```
```{r}
rest <- rest %>% 
  select(id, position, name, score, zip_code, lat, lng) %>% 
  mutate(popular = ifelse(position > 30, 1, 0)) %>% 
  group_by(zip_code) %>% 
  mutate(avgscoreinarea = mean(score, na.rm = TRUE))
rest
```
```{r}
restmen$price <- as.numeric(gsub("\\USD", "", restmen$price))

meann <- restmen %>% 
  ungroup() %>% 
  filter(price > 4) %>%
  filter(price < 100) %>% 
  mutate(mp = mean(price, na.rm = TRUE)) 

restmen <- restmen %>% 
  rename(id = restaurant_id) %>% 
  group_by(id) %>% 
  mutate(avgprice = mean(price, na.rm = TRUE)) %>% 
  mutate(morethanavg = ifelse(price < 12.6, 1, 0))
restmen
```

```{r}
merged <- inner_join(restmen, rest, by = join_by(id))
write_csv(merged, file = "Documents/data/merged.csv")
```
merged$zip_code  <- 
merged %>% 
  select(zip_code) %>% 
  range()
```{r}

states <-map_data("state")
al_df <- subset(states, region == "alabama")

counties <-map_data("county")
ca_county <- subset(counties, region == "alabama")

al <- ggplot(merged, aes(lng, lat)) +
  geom_polygon(data= al_df,aes(x=long,y=lat,group=group),color='gray',fill= "gray",alpha=1)+
  geom_point(aes(col = avgprice),size= .1 ,alpha=.01) +
  xlim(-90,-82.5)+ylim(30.2,35.2)



ca_base <- ggplot(data = al_df, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(color = "black", fill = "gray")

ca_base + 
  ggplot(merged, aes(lng, lat)) +
  geom_point(aes(col = avgprice),size= .1 ,alpha=.01) +
  geom_polygon(data = ca_county, fill = NA, color = "white") +
  geom_polygon(color = "black", fill = NA)

al <- ggplot(merged, aes(lng, lat)) +
  geom_polygon(data = al_df, aes(x = long, y = lat, group = group), color = 'gray', fill = "gray", alpha = 1) +
  geom_point(aes(col = avgprice), size = 0.1, alpha = 0.01) +
  geom_path(data = al_df, aes(x = long, y = lat, group = group), color = 'red', size = 1) +  # Add lines with a different color (e.g., red)
  xlim(-90, -82.5) + ylim(30.2, 35.2)
print(al)

al <- ggplot() +
  geom_polygon(data = al_df, aes(x = long, y = lat, group = group), color = 'gray', fill = "gray", alpha = 1) +
  geom_polygon(data = ca_county, aes(x = long, y = lat, group = group), fill = "gray", color = "white") +
  geom_point(data = merged, aes(x = lng, y = lat, col = avgprice), size = 0.1, alpha = 0.01) +
  geom_path(data = al_df, aes(x = long, y = lat, group = group), color = 'black', size = 1) +  # Add lines with a different color (e.g., red)
  xlim(-90, -82.5) + ylim(30.2, 35.2) +
  coord_fixed(1.3)

# Print the plot
print(al)

```


```{r}
merged  %>% 
  ggplot(aes(position, avgprice)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(x = "Popularity position", y = "")

lm(avgprice ~ position, data = merged)
```
