---
title: "Final Project "
author: "Michelle Ngo, Chunqi Zhao, Kelly Chang, Eunseo Chung"
date: "2023-12-01"
output: html_document
---
```{r}
library(readr)
library(tidyverse)
library(ggplot2)
library(maps)
restaurantmenus <- read_delim("Documents/archive/restaurant-menus.csv")
restmen <- restaurantmenus[1:25000, c(1:5)]
write_csv(restmen, file = "Documents/data/restmen.csv")

restaurant <- read_delim("Documents/archive/restaurants.csv")
rest <- restaurant[1:25000, c(1:11)]
write_csv(rest, file = "Documents/data/rest.csv")
```
```{r}
rest <- rest %>% 
  select(id, position, name, score, zip_code, lat, lng) %>% 
  mutate(popular = ifelse(position > 30, 1, 0)) %>% 
  group_by(zip_code) %>% 
  mutate(avgscoreinarea = mean(score, na.rm = TRUE))
rest
```

```{r}
restmen$price <- as.numeric(gsub("\\USD", "", restmen$price))

meann <- restmen %>% 
  ungroup() %>% 
  filter(price > 4) %>%
  filter(price < 100) %>% 
  mutate(mp = mean(price, na.rm = TRUE)) 

restmen <- restmen %>% 
  rename(id = restaurant_id) %>% 
  group_by(id) %>% 
  mutate(avgprice = mean(price, na.rm = TRUE)) %>% 
  mutate(morethanavg = ifelse(price < 12.6, 1, 0))
restmen
```

Merging Data:
```{r}
merged <- inner_join(restmen, rest, by = join_by(id))
write_csv(merged, file = "Documents/data/merged.csv")
```

Missing Values:
```{r}
merged %>% 
  filter(is.na(description)) %>% 
  n_distinct()

merged %>% 
  filter(is.na(score)) %>% 
  n_distinct()

merged %>% 
  filter(is.na(zip_code)) %>% 
  n_distinct()

merged %>% 
  filter(is.na(avgscoreinarea)) %>% 
  n_distinct()
```

Range:
```{r}
merged %>% 
  summarize(range(id))
merged %>% 
  summarize(range(price))
merged %>% 
  summarize(range(avgprice))  
merged %>% 
  summarize(range(position))
merged %>% 
  summarize(range(score, na.rm = TRUE))
merged %>% 
  summarize(range(avgscoreinarea, na.rm = TRUE))
```

Summarization Data Frame:
```{r}
sumdf <- data.frame(
  Variable = c("id", "price", "avgprice", "position", "score", "avgscoreinarea"),
  Minimum = c(1, 0, 0, 1, 3.2, 3.5),
  Maximum = c(363, 130.89, 34, 194, 5.0, 5.0),
  Missing_Value = c(0, 0, 0, 0, 9141, 977)
)
sumdf
```

What is the range of meal prices?
```{r}
merged %>% 
  filter(!(price == 0)) %>% 
  arrange(price) %>%
  filter(rank(desc(price)) < 5 | rank(price) < 5) %>% 
  select(id, category, name.x, price, score, zip_code)
```

What is the highest score? What are the restaurants? 
```{r}
merged %>% 
  filter(score != "-Inf" & score == 5.0) %>% 
  distinct(id, name.y, score)
```

What is the relationship between zip code and the average price of the restaurants?
```{r}
states <-map_data("state")
al_df <- subset(states, region == "alabama")

counties <-map_data("county")
ca_county <- subset(counties, region == "alabama")

al <- ggplot() +
  geom_polygon(data = al_df, aes(x = long, y = lat, group = group), color = 'gray', fill = "gray", alpha = 1) +
  geom_polygon(data = ca_county, aes(x = long, y = lat, group = group), fill = "gray", color = "white") +
  geom_point(data = merged, aes(x = lng, y = lat, col = avgprice, size = avgprice), alpha = 0.01) +
  geom_path(data = al_df, aes(x = long, y = lat, group = group), color = 'black', size = 1) +  # Add lines with a different color (e.g., red)
  xlim(-90, -82.5) + ylim(30.2, 35.2) +
  coord_fixed(1.3) +
  labs(x = "Longitude", y = "Latitude", title = "Average price vs. zip code", col = "Average price")
al
```
```{r}
al <- ggplot() +
  geom_polygon(data = al_df, aes(x = long, y = lat, group = group), color = 'gray', fill = "gray", alpha = 1) +
  geom_polygon(data = ca_county, aes(x = long, y = lat, group = group), fill = "gray", color = "white") +
  geom_point(data = merged, aes(x = lng, y = lat, col = avgprice, size = avgprice), alpha = 0.01) +
  geom_path(data = al_df, aes(x = long, y = lat, group = group), color = 'black', size = 1) +  # Add lines with a different color (e.g., red)
  xlim(-87, -85.5) + ylim(34.5, 33) +
  coord_fixed(1.3) +
  labs(x = "Longitude", y = "Latitude", title = "Average price vs. zip code", col = "Average price")
al
```

 What is the relationship between position popularity and the price of the meal?
```{r}
merged  %>% 
  ggplot(aes(position, avgprice)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(x = "Popularity position", y = "")

lm(avgprice ~ position, data = merged)
```




